version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g next
  pre_build:
    commands:
      - npm install
      - npm list --depth=0
  build:
    commands:
      - npm run export
  post_build:
    commands:
artifacts:
  files:
    - out/**/*
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths